### PR TITLE
Fixed deprecated theme properties

### PR DESCRIPTION
**Pull request by CrisNegoianu**
Hi.

The latest flutter update on the build channel has removed a few deprecated theme properties.
This update fixes them.

### CODE REVIEW

**Review by realkalash — APPROVED** [review]

**Comment by Mapk26** [comment]
This should be merged ASAP

**Comment by rodydavis** [comment]
Can you fix the conflicts? Then I will merge and publish!

**Review by rodydavis — APPROVED** [review]

**Comment by rodydavis** [comment]
LGTM

**Comment by rodydavis** [comment]
published 1.4.0!

**Pull request merged**
